CREATE TABLE CATEGORIA(
    codigo SERIAL PRIMARY KEY,
    nome CHARACTER VARYING(100)
);

INSERT INTO CATEGORIA (nome) VALUES ('Lazer');
INSERT INTO CATEGORIA (nome) VALUES ('Alimentação');
INSERT INTO CATEGORIA (nome) VALUES ('Supermercado');
INSERT INTO CATEGORIA (nome) VALUES ('Farmácia');
INSERT INTO CATEGORIA (nome) VALUES ('Outros');